### ISSUE TITLE
PlatformException on Android Device

### ISSUE THREAD

**Issue by metinbinbir** [nfcim/flutter_nfc_kit#100]
I am using dmrtd flutter package to read driver licence with NFC, and it is using flutter_nfc_kit with methodchannel. However, in transceive function, it gives Unhandled Exception: PlatformException(500, Communication error, null, null) error. What should I do?

**Comment by sant0s** [comment]
@metinbinbir is the command you're transceiving correct and does the tag support it?

**Comment by metinbinbir** [comment]
@sant0s my command was invalid, thanks for the help.
