### ISSUE TITLE
iOS overlay top line configuration

### ISSUE THREAD

**Issue by sant0s** [nfcim/flutter_nfc_kit#103]
during tag scanning on iOS, there's an overlay that includes:

1. a top line of text like "Ready to read"
2. an animated image of a device moving
3. a bottom line of text like "Hold your iPhone near the card"

`iosAlertMessage` within `FlutterNfcKit.poll()` configures 3. is there a way to configure 1.?

**Comment by jiegec** [comment]
Nope, according to [iOS documentation](https://developer.apple.com/documentation/corenfc/nfcreadersessionprotocol/2919987-alertmessage), you can only set the `alertMessage`.
