### ISSUE TITLE
iOS overlay removal

### ISSUE THREAD

**Issue by sant0s** [nfcim/flutter_nfc_kit#104]
during tag scanning on iOS, there's an overlay that includes a top line of text like "Ready to read", an animated image of a device moving and a bottom line of text like "Hold your iPhone near the card".

is there a way to remove this overlay altogether?

**Comment by jiegec** [comment]
I don't think so, this popup is shown by iOS.

**Comment by sant0s** [comment]
thanks. while some sources indicate that's indeed [not possible](https://stackoverflow.com/questions/47708668/how-to-remove-popup-message-of-nfc-tag-in-ios), others hint [otherwise](https://stackoverflow.com/questions/50464810/is-it-possible-to-hide-ios-system-alert-for-nfc-reading-session).

**Comment by jiegec** [comment]
> thanks. while some sources indicate that's indeed [not possible](https://stackoverflow.com/questions/47708668/how-to-remove-popup-message-of-nfc-tag-in-ios), others hint [otherwise](https://stackoverflow.com/questions/50464810/is-it-possible-to-hide-ios-system-alert-for-nfc-reading-session).

The post suggests that the popup can be hidden automatically **after** scanning the card, but not before.

**Comment by sant0s** [comment]
That's right. Closing this issue.
