### ISSUE TITLE
skipping nfcAvailability()

### ISSUE THREAD

**Issue by sant0s** [nfcim/flutter_nfc_kit#105]
instead of first checking NFC availability via `nfcAvailability()` and then, if NFC is available, calling `poll()`, I am thinking about calling `poll()` directly to speed things up: if `poll()` returns 404, then it means that NFC is not available.

Do you see any problem with this approach?

**Comment by Harry-Chen** [comment]
I do not think `nfcAvailability` can replaced totally, however you *can* skip checking and rely on the errors returned by other methods.
