### ISSUE TITLE
nfc_kit compatibility issue with nfc manager library in andriod 13

### ISSUE THREAD

**Issue by Rahul123723** [nfcim/flutter_nfc_kit#107]
flutter_nfc_kit ^3.3.1 which provide NFC funtionality on Andriod ,ios and web facing problem with andriod 13version . when we use nfc manager also with it in a project where as nfc manager is also a plugin for accessing the NFC features on andriod and ios it is throwing exception[](url)
![exception thrown](https://github.com/nfcim/flutter_nfc_kit/assets/141919808/0a7ebe0e-9722-4b6f-b95c-d660d0127a8b)

**Comment by Rahul123723** [comment]
``` 
![Screenshot (1)](https://github.com/nfcim/flutter_nfc_kit/assets/141919808/095db8d2-7371-47ae-9596-8d934ea8fb0e)

**Comment by Rahul123723** [comment]
![exception thrown](https://github.com/nfcim/flutter_nfc_kit/assets/141919808/cb1a8438-5820-4759-8a2d-76a37d6472a8)

**Comment by Harry-Chen** [comment]
Duplicated with https://github.com/nfcim/flutter_nfc_kit/issues/90

**Comment by Rahul123723** [comment]
i have tried with your suggested changes if i am able to use both the library in andriod 13 and  all session also ending properly one session is stops

**Comment by Rahul123723** [comment]
my issue is not duplicated from anyone's other this is the issue which i am facing while working with the two nfc manager and nfc kit library
