### ISSUE TITLE
read Error Toast on Android 10

### ISSUE THREAD

**Issue by DanielPfannes** [nfcim/flutter_nfc_kit#11]
Hello again,

I have encountered another issue while using NFC Reader mode in your plugin on Android 10. There is sometimes a toast shown with 
_"NFC read error. Try again."_ Despite the reader Mode API polled the TAG successfully.

![image](https://user-images.githubusercontent.com/40307553/90271249-c82cf080-de5b-11ea-94dc-bcc4b69a3a41.png)

This toast is generated by the Android NFC service itself when checking for NDEF Tags.  
see here in [Android Documentation](https://android.googlesource.com/platform/packages/apps/Nfc/+/master/src/com/android/nfc/NfcService.java#2259)

Currently I'm not using any NDEF Tags in my app so I would like to skip the NDEF Check which can be done by setting the reader Flag:
**FLAG_READER_SKIP_NDEF_CHECK** in reader Mode [see here](https://developer.android.com/reference/android/nfc/NfcAdapter#FLAG_READER_SKIP_NDEF_CHECK) . 

Could you please extend your plugin with an option to set this flag?

**Comment by Harry-Chen** [comment]
Thanks for the advice!
