### ISSUE TITLE
transceive: distinguishing between tag lost and unsupported command

### ISSUE THREAD

**Issue by sant0s** [nfcim/flutter_nfc_kit#113]
`FlutterNfcKit.transceive()` may throw `PlatformException` with code `500` which indicates that either

1. the tag was lost while being read
1. the tag does not understand the command

is there any way to distinsguish between 1. and 2.? if not, how would you solve this problem? the goal would be to display a meaningful message to the user depending on the scenario:

1. for a lost tag: "try not to move the device while reading the tag"
2. for an unsupported command: "the tag does not understand the command"

while testing, i noticed that, for `PlatformException.code` `500` and `PlatformException.message` `Communication error`, `PlatformException.details` varies:

- `Transceive failed`
- `Tag was lost.`
- `null`

this doesn't seem to allow doing the distinction though: for tags supporting a given command, all these values mean "lost tag".

**Comment by Harry-Chen** [comment]
Thanks for your advice!

Certainly we all want more specific types of errors. But to the best of my knowledge, neither on Android nor iOS, can we distinguish these types of errors you mentioned from the exception / error returned by system APIs, except for matching hardcoded error messages.

But we are still trying our best to distinguish from `flutter_nfc_kit` side: the library will return `405` when it believes some operation is not supported by the tag. But when the requests go further into system APIs, there seems nothing much we can do.
