### ISSUE TITLE
pubspec version and github tag version not aligned

### ISSUE THREAD

**Issue by kyeshmz** [nfcim/flutter_nfc_kit#121]
Hi, it seems that the current pub dev version is pulling 3.2, while it says that there is a 3.3.3 version available.
In the github, it seems that there is no tag for 3.3.3.

I saw this because the current example in github has mifareinfo included in the NfcTag class, but running the current example using the pub dev version does not.

**Comment by Harry-Chen** [comment]
Sorry, actually I forgot to push v3.3.3 tag to GitHub.

As for Mifare support, it will be included in next minor version (maybe v3.4.0) later this month (if I can make it).

**Comment by Harry-Chen** [comment]
Now `v3.3.3` is pushed to GitHub.
