### ISSUE TITLE
Unhandled Exception: type 'String' is not a subtype of type 'Map<String, dynamic>' in type cast

### ISSUE THREAD

**Issue by adiwirya** [nfcim/flutter_nfc_kit#126]
i use flutter_nfc_kit 3.4.1
i got this error when taping my card to nfc reader 

E/flutter ( 7380): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'String' is not a subtype of type 'Map<String, dynamic>' in type cast
E/flutter ( 7380): #0      _$NFCTagFromJson
flutter_nfc_kit.g.dart:47
E/flutter ( 7380): #1      new NFCTag.fromJson
flutter_nfc_kit.dart:145
E/flutter ( 7380): #2      FlutterNfcKit.poll
flutter_nfc_kit.dart:344
E/flutter ( 7380): <asynchronous suspension>

this is the code 
     json['mifareInfo'] == null
          ? null
          : MifareInfo.fromJson(json['mifareInfo'] as Map<String, dynamic>),
    );

**Comment by Harry-Chen** [comment]
Which platform are you on, Android or iOS?

**Comment by Harry-Chen** [comment]
Please check whether cc5c098 fixes this problem.

**Comment by martijn00** [comment]
@Harry-Chen you that fixes the problem. Thanks!

**Comment by martijn00** [comment]
Can you release a new version to pubdev?

**Comment by Harry-Chen** [comment]
Now version 3.4.2 has been released. Sorry for the delay.

**Comment by n0dz** [comment]
Hi there, on google pixel 6 it still opens the default nfc reader app I am using the 3.4.2 version of the plugin
