### ISSUE TITLE
poll() method: String is not a subtype of Map<String, dynamic>

### ISSUE THREAD

**Issue by M-Ahal** [nfcim/flutter_nfc_kit#133]
<img width="548" alt="image" src="https://github.com/nfcim/flutter_nfc_kit/assets/132486634/9f2454fb-9fbc-4be9-a400-0e8fef4f4892">

The received MifareInfo value is actually a string-repsrestation of a Map(Json). The easy fix is to do a `json.decode()` before passing it to the `MifareInfo.fromJson()`.

**Comment by Harry-Chen** [comment]
Duplicated with #126

**Comment by M-Ahal** [comment]
@Harry-Chen Is the new version not near-ready for release yet?

**Comment by Harry-Chen** [comment]
Since some functionality we planned is not ready yet, I will release a new version soon to fix this.
