### ISSUE TITLE
How to check if device have NFC ?

### ISSUE THREAD

**Issue by Suheb786** [nfcim/flutter_nfc_kit#138]
there are two checks that i want to implement - 

1- check if user's device have NFC 
2- check if user's has disabled or enabled the NFC 

Note- available method only provide if the NFC is enable or disabled, what about the first check

**Comment by ivangalkindeveloper** [comment]
The method gives an enumeration that already shows support and current operation of the NFC module on the device
 
```
 enum NFCAvailability {
  not_supported,
  disabled,
  available,
}

final NFCAvailability nfcAvailability = await FlutterNfcKit.nfcAvailability;
```
