### ISSUE TITLE
Missing 'id' field in FeliCa card reading on iOS

### ISSUE THREAD

**Issue by shiwano** [nfcim/flutter_nfc_kit#139]
Hi,

When trying to read a FeliCa card (in my case, a Japanese SUICA) on iOS, I encounter the below error.

```
flutter: type 'Null' is not a subtype of type 'String' in type cast
flutter: #0      _$NFCTagFromJson (package:flutter_nfc_kit/flutter_nfc_kit.g.dart:28:18)
#1      new NFCTag.fromJson (package:flutter_nfc_kit/flutter_nfc_kit.dart:142:57)
#2      FlutterNfcKit.poll (package:flutter_nfc_kit/flutter_nfc_kit.dart:336:19)
```

I've confirmed that the JSON returned from the native side looks like the below.

```json
{
  "type": "iso18092",
  "ndefCanMakeReadOnly": false,
  "manufacturer": "****************",
  "ndefType": "",
  "ndefAvailable": false,
  "ndefCapacity": 0,
  "systemCode": "0003",
  "standard": "ISO 18092 (FeliCa)",
  "ndefWritable": false,
}
```

It seems that the error occurs at the following line because there is no `id` field.

https://github.com/nfcim/flutter_nfc_kit/blob/cc5c098700e618ba5629dbc33a00fce1cae12863/lib/flutter_nfc_kit.g.dart#L28

When I added the `id` field, the error no longer occurred in my environment.

**Comment by Harry-Chen** [comment]
Closed by #140
