### ISSUE TITLE
Error reading tag 15693 in iOS

### ISSUE THREAD

**Issue by portu86** [nfcim/flutter_nfc_kit#143]
Hello!
I am working with a 15693 tag and I am trying to read some blocks. In Android works perfectly but when I try to launch it on iOS I always receive the response [255,255].
I received the same response when I tried to send present password.

Here is the code:

 
`        NFCTag tag = await FlutterNfcKit.poll(timeout: Duration(seconds: 15), readIso14443A: false, readIso14443B: false);
        setState((){
	_tag = tag;
	});
	if(tag.type == NFCTagType.iso15693){
	
	UintList ComandoR = UintList(20);
	ComandoR[0] = 0x22; //Flag
	ComandoR[1] = 0xB3; //Present password
	ComandoR[2] = 0x02; //IC Mfg code
	
	//Uid
	ComandoR[3] = 0x55;
	...
	ComandoR[10] = 0xE0;
	
	ComandoR[11] = 0x01; //Password 1
	
	//Password
	ComandoR[12] = 0x12;
	...
	ComandoR[19] = 0x56;
	
	UintList result8 = await FlutterNfcKit.transceive(ComandoR);
	String result1 = result8.toString();
	resFinal = result1;
	setState((){
		_result = '1: $result1\n';
	});
`
	
	
	The response is [255, 255] always. It doesn't matter if I sent the password or I try to read blocks.

what am I doing wrong? Is it possible to work in iOS like in Android (transcieve raw commands)?

Thank you in advance!

**Comment by Harry-Chen** [comment]
Maybe #150 will help.
