### ISSUE TITLE
Support Java 17

### ISSUE THREAD

**Issue by larssn** [nfcim/flutter_nfc_kit#154]
So using Gradle 8+ and the newest Gradle setup for Flutter, I get an error building a project that uses flutter_nfc_kit:
`Inconsistent JVM-target compatibility detected for tasks 'compileDebugJavaWithJavac' (17) and 'compileDebugKotlin' (11)`

It doesn't seem to matter whether I set `sourceCompatibility` to `JavaVersion.VERSION_11` or `JavaVersion.VERSION_17` in my `app/build.gradle`.

The workaround for now is adding the following to the bottom of `android/build.gradle`, replacing the existing:
```groovy
rootProject.buildDir = '../build'
subprojects {
    afterEvaluate {
        if (project.plugins.hasPlugin("com.android.application")
                || project.plugins.hasPlugin("com.android.library")) {
            if (project.name == "flutter_nfc_kit") {
                project.android.compileOptions {
                    sourceCompatibility = JavaVersion.VERSION_17
                    targetCompatibility = JavaVersion.VERSION_17
                }
            }
        }
    }
}

subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}
```

**Comment by Harry-Chen** [comment]
Thanks! Please track it in #127.
