### ISSUE TITLE
writeNDEFRecords to Specify block

### ISSUE THREAD

**Issue by Saintqqq** [nfcim/flutter_nfc_kit#165]
hi 

how to write NDEFRecord to specify block, not use transceive?

the sample code is working, but can't write to specify block
 
```
List<ndef.NDEFRecord>? _records;
    _records = [
      ndef.TextRecord(
          encoding: ndef.TextEncoding.UTF8,
          language: "zh",
          text: "hi jane"),
    ];

await FlutterNfcKit.writeNDEFRecords(_records);
```

is anything suggest?
thanks

**Comment by Harry-Chen** [comment]
When you write NDEF records to a tag, it uses a higher layer of abstraction and does not have the concept of "blocks".

If you **do want to write raw NDEF data** to a "block", use:

```dart
var record = ndef.TextRecord();
var encodedNdefRecord = record.encode();
await FlutterNfcKit.writeBlock(1, encodedNdefRecord);
```
