### ISSUE TITLE
bug: race conditions with multiple operations in succession

### ISSUE THREAD

**Issue by knthm** [nfcim/flutter_nfc_kit#166]
On MIFARE Classic I've observed `authenticateSector` calls failing when called directly after `writeBlock`. Inserting a few milliseconds delay between the method calls fixed the issue.

After further investigation, I've determined that in the failure case, `authenticateSector` is called while the `writeBlock` call hasn't yet completed, this is because we spawn a new thread for every IO operation.

**Comment by Harry-Chen** [comment]
Many thanks for make our code more safe! The one-thread-per-call design is easy to implement, but in deed brings overhead and some potential races. A handler would be elegant to solve this.

But if I understand correctly, the `Future` on the Flutter side will not resolve until native code calls `result.success` or `result.error`. So if you `await` on each call to `FlutterNfcKit`, such race conditions are not expected to happen.

**Comment by knthm** [comment]
> But if I understand correctly, the Future on the Flutter side will not resolve until native code calls result.success or result.error. So if you await on each call to FlutterNfcKit, such race conditions are not expected to happen.

All my `FlutterNfcKit.*` method calls are prefixed with await, but you're right, the way the `MethodChannel` result stuff words should prevent any simultaneous IO operations when await is used.
I think I might've gotten the issue mixed up with some other strange behavior around the `authenticateSector` call after `writeBlock`. These seem to be specific to the tag operational logic and not this library though. 

However, running the operations in a dedicated thread will prevent accidental simultaneous calls, as well as being a bit more performant, since we don't have the overhead of spawning a new thread for every operation.
