### ISSUE TITLE
iOS NFCISO7816APDU instantiation method

### ISSUE THREAD

**Issue by cd-chen** [nfcim/flutter_nfc_kit#173]
I found that NFCISO7816APDU can only be instantiated through data 

`NFCISO7816APDU? = NFCISO7816APDU(data: data)`

Now I have a requirement that needs to be instantiated in the following way

```
NFCISO7816APDU(
        instructionClass: arguments["instructionClass"] as! UInt8,
        instructionCode: arguments["instructionCode"] as! UInt8,
        p1Parameter: arguments["p1Parameter"] as! UInt8,
        p2Parameter: arguments["p2Parameter"] as! UInt8,
        data: (arguments["data"] as! FlutterStandardTypedData).data,
        expectedResponseLength: arguments["expectedResponseLength"] as! Int
      )
```

Is there any good way for me to do this?

**Comment by dangfan** [comment]
This is not related to our library. You may ask your question at https://developer.apple.com/forums/
