### ISSUE TITLE
new problem when trying to add this package 

### ISSUE THREAD

**Issue by yaakoubDj** [nfcim/flutter_nfc_kit#174]
when i try to add this package to my project i get a lot of errors the most about Kotlin version , when i remove this package and try again everything work !! , so the problem in this package , i hope fix it because i need this package to get id of NFC tag.

**Comment by markHamilton34** [comment]
#158 This could help you.

**Comment by dpsavaliya** [comment]
same issue. Is there any solution?

**Comment by dpsavaliya** [comment]
> #158 This could help you.

Not working

**Comment by Harry-Chen** [comment]
> when i remove this package and try again everything work !! , so the problem in this package

Not necessarily. Would you please provide a minimal reproducing code? E.g. the Kotlin and Flutter version you are using, other dependencies, and the specific errors you got.

**Comment by dpsavaliya** [comment]
I have solved the issue by changing the kotlin version to `"1.9.23"` in `flutter_project/android/setting.gradle` file. 

`plugins {
    id "org.jetbrains.kotlin.android" version "1.9.23" apply false
}`

I'm commenting in case someone else has the same issue.

**Comment by Harry-Chen** [comment]
The the problem is related to incompatible Kotlin version, mostly because the Kotlin gradle plugin you are using is too old. Good to see that you have solved it.
