### ISSUE TITLE
how about to send apdu(hex string) with spaces seperated 

### ISSUE THREAD

**Issue by dotnfc** [nfcim/flutter_nfc_kit#177]
for coding a hex c-apdu, we may use spaces to sperate the cla, ins, p1, p2, ... such as:
"00a4 0400 08 a0000000 03000000". so, how about to change 'flutter_nfc_kit.dart' with

```dart
  static Future<T> transceive<T>(T capdu, {Duration? timeout}) async {
    assert(capdu is String || capdu is Uint8List);
    
    if (capdu is String) {                  <---
      capdu = capdu.replaceAll(" ", "");    <---
    }                                       <---
   ...
```

**Comment by Harry-Chen** [comment]
Instead of modifying the library, I think it is better to write a function that wraps `transceive` yourself to do any transformation you want.
