### ISSUE TITLE
Click the settings, not skip to the NFC setting moudle

### ISSUE THREAD

**Issue by SunLees** [nfcim/flutter_nfc_kit#178]
![image](https://github.com/nfcim/flutter_nfc_kit/assets/20698985/4ac9e168-cc62-4edb-8c0d-fd4850de5d1f)

点击弹框中的设置按钮，没有跳转到系统设置页面，而且这个弹框为什么会是英文的？

**Comment by SunLees** [comment]
设备信息：

**Comment by Harry-Chen** [comment]
您描述的问题和本库看起来没有关系，请联系应用开发者。

**Comment by SunLees** [comment]
> 您描述的问题和本库看起来没有关系，请联系应用开发者。

NFCTag nfcTag = await FlutterNfcKit.poll(iosAlertMessage: "准备扫描，将标签贴近手机");

我直接使用的这个方法拉起NFC识别，这个弹框应该是插件内部给到的吧

**Comment by Harry-Chen** [comment]
这不是插件弹出的对话框。iOS 的实现请见 https://github.com/nfcim/flutter_nfc_kit/blob/master/ios/Classes/SwiftFlutterNfcKitPlugin.swift 。

**Comment by SunLees** [comment]
> 这不是插件弹出的对话框。iOS 的实现请见 https://github.com/nfcim/flutter_nfc_kit/blob/master/ios/Classes/SwiftFlutterNfcKitPlugin.swift 。

好的   谢谢了！   主要是部分机型才会出现这个问题。
