### ISSUE TITLE
Flutter Web, external NFC Reader does not connect in Chrome

### ISSUE THREAD

**Issue by MatthiasMAigner** [nfcim/flutter_nfc_kit#181]
Hi,

First off, I'd like to extend my heartfelt appreciation for your work on the flutter_nfc_kit plugin. It's fantastic, and I've found it extremely useful in my projects.

I'm reaching out to inquire about the plugin's capabilities concerning web support, specifically when using external NFC readers with browsers like Chrome. I've been trying to connect an external NFC reader, but so far, I haven't had any success in getting it recognized by the browser.

Could you provide some guidance on what characteristics an external NFC reader should have to be compatible with your plugin on web platforms? Additionally, if you have any recommendations for NFC readers that are known to work well with this setup, that information would be greatly appreciated.

Thank you for your time and assistance.

Best regards,
Matthias Aigner

**Comment by dangfan** [comment]
Hi Matthias,
Thank you for your kind words about the flutter_nfc_kit plugin! I'm glad to hear that you find it useful for your projects.
Regarding your inquiry about web support for external NFC readers, I want to clarify that WebUSB does not support the CCID interface. Unfortunately, this means that you won't be able to connect your external NFC reader directly through the browser.
One possible workaround is to run a local program that starts an HTTP server. This server can handle APDU commands and facilitate communication with the NFC reader. This approach might help you achieve the functionality you need.
