### ISSUE TITLE
FeliCa IDm cannot be obtained.

### ISSUE THREAD

**Issue by HpYama** [nfcim/flutter_nfc_kit#183]
NFCTag tag = await FlutterNfcKit.poll();
After polling the tag, I checked tag.id.

In the case of ISO15693 and ISO14443TypeA, all IDs were obtained.
However, in the case of FeliCa, all IDs could not be obtained.

Specifically, FeliCa's IDm is 16 digits, but only 8 digits are stored in tag.id.

**Comment by Harry-Chen** [comment]
On Android, there is no API to read the full IDm, only <https://developer.android.com/reference/android/nfc/tech/NfcF#getManufacturer()>.

You can always use raw `Get FeliCa ID` commands via `transceive` to get the full IDm and PMm.

**Comment by HpYama** [comment]
Thank you for your quick reply.

I apologize for the lack of explanation.
I am using iOS.

I understand that it is difficult to obtain all FeliCa IDm using flutter_nfc_kit.

**Comment by Harry-Chen** [comment]
> Thank you for your quick reply.
> 
> I apologize for the lack of explanation. I am using iOS.

On iOS, we directly read from [currentIDm](https://developer.apple.com/documentation/corenfc/nfcfelicatag/3043776-currentidm). So it might be limitation of iOS app.

> I understand that it is difficult to obtain all FeliCa IDm using flutter_nfc_kit.

Not actually. As I mentioned, you can always send raw commands.
