### ISSUE TITLE
can't write command on Android on NFC chip ISO 15693

### ISSUE THREAD

**Issue by romanpavlenko** [nfcim/flutter_nfc_kit#185]
Flutter application correct read/write ISO 15693 chip on iOS but have PlatformException(408, Polling tag timeout, null, null) on android platform on same NFC device

**Comment by Harry-Chen** [comment]
It does not look like a problem on `flutter_nfc_kit` side. Maybe you can try native code first and confirm whether that works?

**Comment by romanpavlenko** [comment]
You are absolutely right, I had to use the transive() method with a custom package implementation for the Android platform
