### ISSUE TITLE
Append NEDFRecord

### ISSUE THREAD

**Issue by Saintqqq** [nfcim/flutter_nfc_kit#188]
hi i have a issue, i need write ndef message to my nfc, but i need repeat writing old meesage.

how can i append new ndef record after old record instead of write two ndef record

thanks

`

        List<ndef.NDEFRecord> records = [
          ndef.TextRecord(
              encoding: ndef.TextEncoding.UTF8, language: "aa", text: event.message),

          ndef.TextRecord(
              encoding: ndef.TextEncoding.UTF8, language: "aa", text: event.message2)
        ];
        await FlutterNfcKit.writeNDEFRecords(records);

`

**Comment by Harry-Chen** [comment]
No API provides such functionality on either Android or iOS. You will need to read the current records, append a new one, and write them back.
