### ISSUE TITLE
When reading tags on Android devices, a system pop-up window will pop up

### ISSUE THREAD

**Issue by laoduan395** [nfcim/flutter_nfc_kit#194]
Samsung galaxy A15 5G

![image](https://github.com/user-attachments/assets/4743b574-ce9d-46e7-9058-ab7e0267bd9a)

Mi 10T Pro
![image](https://github.com/user-attachments/assets/6bb822df-a51a-46de-9bf0-d3a2dff3af0c)

As shown in the figure, my program runs normally and the NFC Tag recognizes the data normally, but how can I avoid the system pop-up trigger? thx

**Comment by Harry-Chen** [comment]
Duplicated with #17.
