### ISSUE TITLE
App crash when run on ios 14.1

### ISSUE THREAD

**Issue by saobang187** [nfcim/flutter_nfc_kit#21]
Hi Sir,
I followed the setup in pub.dev for ios(add to Info.plist file), but the app crash when going to the widget using FlutterNfcKit.poll or FlutterNfcKit.transceive, then NFCAvailability.available work ok only. I don't know how to fix this issue, many thank if you can help me resolve it. I using nfc ISO7816 for NXP smart card.
Thanks,
The Anh

**Comment by dangfan** [comment]
Do you have any related logs?

**Comment by saobang187** [comment]
Yes sir, all config file and debug log after disconnect device.
![Ảnh chụp Màn hình 2020-11-28 lúc 09 39 23](https://user-images.githubusercontent.com/54204953/100492723-8d786b00-3161-11eb-9879-a99f6d744682.png)
![Ảnh chụp Màn hình 2020-11-28 lúc 09 40 15](https://user-images.githubusercontent.com/54204953/100492728-910bf200-3161-11eb-9df8-ef1df860f7ed.png)
![Ảnh chụp Màn hình 2020-11-28 lúc 09 40 45](https://user-images.githubusercontent.com/54204953/100492730-92d5b580-3161-11eb-93a5-34f67390c1ee.png)
![Ảnh chụp Màn hình 2020-11-28 lúc 10 02 43](https://user-images.githubusercontent.com/54204953/100492731-936e4c00-3161-11eb-80d1-9f8cc6217627.png)

**Comment by saobang187** [comment]
@dangfan maybe channel name error because I change channel name by other string then app don't crash, but it don't send data to card until.
![Ảnh chụp Màn hình 2020-11-28 lúc 16 54 59](https://user-images.githubusercontent.com/54204953/100499277-d0a30000-319a-11eb-8924-47198b6b751c.png)

**Comment by dangfan** [comment]
@saobang187 From the information you provided, we couldn't figure out what happened. Would you please provide a minimal reproducible example? Thanks!

**Comment by saobang187** [comment]
@dangfan i use your code in pub.dev(you can see in images), and call cardConnect method(use FlutterNfcKit.poll with parameters for ios) in the initState of a widget(you can create any widget and add this), app crash when go to line FlutterNfcKit.poll, i tested on iphone7 plus and xs.

**Comment by saobang187** [comment]
@dangfan apple support Read NFC for smartMx3 NXP, i try NFC other tag then it work ok, so I will close this issue at here. Thanks you
