### ISSUE TITLE
Bump json_annotation version

### ISSUE THREAD

**Issue by mbartn** [nfcim/flutter_nfc_kit#27]
Bumping `json_annotation` version from `3.x` to `4.x` will make the library compatible with other plugins that already did, for example [Device preview](https://pub.dev/packages/device_preview)

**Comment by jiegec** [comment]
We need to bump ndef first.

**Comment by jiegec** [comment]
Done in commit ab6a3ba

**Comment by mbartn** [comment]
I bumped plugin version to `2.2.1` and looks like everything works fine, thanks!
