### ISSUE TITLE
NFC not working on Android 10, 11

### ISSUE THREAD

**Issue by jafar260698** [nfcim/flutter_nfc_kit#40]
It is not detecting anything on Symsung  A51, A71. what should i do, are there anything special for them ?

**Comment by Harry-Chen** [comment]
Sorry but we do not have Samsung devices. Do you mean you can see NFC enabled but cannot poll tags?

**Comment by jafar260698** [comment]
Yeah , it is not polling anythig, also it is not throwing anthing

**Comment by Harry-Chen** [comment]
This is very strange, can you see anything unnormal in Flutter debug log? Are you sure you add the technologies (such as NFCA, MirareClassic` to your manifest? Can other applications read cards (such as TagInfo by NXP)?

**Comment by jafar260698** [comment]
It is giving such error 

-------------++ PlatformException(500, Communication error, Tag was lost., null) #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597:7)
I/flutter ( 7187): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
I/flutter ( 7187): <asynchronous suspension>
I/flutter ( 7187): #2      FlutterNfcKit.transceive (package:flutter_nfc_kit/flutter_nfc_kit.dart:225:12)
I/flutter ( 7187): <asynchronous suspension>
I/flutter ( 7187): #3      NFCCardChannel.transmit (package:Eimzo/provider/nfc_provider.dart:16:21)
I/flutter ( 7187): <asynchronous suspension>

**Comment by Harry-Chen** [comment]
Sorry for the late reply, please check:

* What option are you using for `poll`?
* Can other applications, such as TagInfo, poll tags normally?

**Comment by hebaothman** [comment]
What's the solution please?

**Comment by Harry-Chen** [comment]
We have no Samsung devices, and we are not able to reproduce the problem on other devices.

Should anyone answer the question in https://github.com/nfcim/flutter_nfc_kit/issues/40#issuecomment-926642090, we might be able to proceed with the problem.

**Comment by kauemurakami** [comment]
2025 with xiaomi redmi note 8 the same error when write, any solutions?
