### ISSUE TITLE
Not showing any credit card details 

### ISSUE THREAD

**Issue by UmaiZ** [nfcim/flutter_nfc_kit#44]
I have version 3.0.2 I am trying to ready credit card data but it's showing Transceive Result null. I have tried multiple cards but it's not showing any card information just display NFC details etc. Is this plugin to show card info or not? I confirm with apps that are correctly showing my card data through NFC but this is showing null on all my cards.

**Comment by jiegec** [comment]
Are you using iOS or Android?

**Comment by UmaiZ** [comment]
> Are you using iOS or Android?

Using Android.
