### ISSUE TITLE
error transceive on ios NSLocalizedDescription=Missing required entitlement, on android working

### ISSUE THREAD

**Issue by sabardotnet** [nfcim/flutter_nfc_kit#46]
{"type":"iso7816","standard":"ISO 14443-4 (Type A)","id":"AF5AB23C","atqa":null,"sak":null,"historicalBytes":"","hiLayerResponse":null,"protocolInfo":null,"applicationData":null,"manufacturer":null,"systemCode":null,"dsfId":null,"ndefAvailable":false,"ndefType":"","ndefCapacity":0,"ndefWritable":false,"ndefCanMakeReadOnly":false}
[CoreNFC] 00000002 83905200 -[NFCTagReaderSession transceive:tagUpdate:error:]:771  Error Domain=NFCError Code=2 "Missing required entitlement" UserInfo={NSLocalizedDescription=Missing required entitlement}

i've added 
	<key>com.apple.developer.nfc.readersession.formats</key>
	<array>
		<string>NDEF</string>
		<string>TAG</string>
	</array>

in Runner.entitlements

**Comment by jiegec** [comment]
@sabardotnet please follow the instructions in README
