### ISSUE TITLE
ByteUtils.kt: (12, 24): Unresolved reference: uppercase

### ISSUE THREAD

**Issue by jafar260698** [nfcim/flutter_nfc_kit#47]
After upgrading package, I come across this error , I guess this error occured in ByteUtils.kt file.
How can i solve this, could you help me ?
![image](https://user-images.githubusercontent.com/65735681/137469598-cff04809-5145-41d9-81b0-8ba4c53c497d.png)

**Comment by Harry-Chen** [comment]
@jafar260698 Please upgrade Kotlin version to >= 1.5 in your android build.gradle.
