### ISSUE TITLE
Does this work on rfid tags ?

### ISSUE THREAD

**Issue by Ghost562562** [nfcim/flutter_nfc_kit#50]
I could not read an rfid tag by using this app. Is there any restrictions ?

**Comment by dangfan** [comment]
What kind of tag are you reading? And what platform are you using?

**Comment by Ghost562562** [comment]
Im trying to write an application for handheld devices(like m3 mobile). Device has own RFID reader. I just need a custom application to catch the data from reader. Tags are UHF.

**Comment by dangfan** [comment]
Unfortuantely, UHF tags cannot be supported by an ordinary mobile phone.
