### ISSUE TITLE
unespected alert for user on scan 

### ISSUE THREAD

**Issue by a-sapuppo** [nfcim/flutter_nfc_kit#57]
hello,

as soon as the scan with the `pool` procedure is finished, this screen appears. why ?
can it hide?

![newtag_20211213-091947](https://user-images.githubusercontent.com/96046672/145777847-604fb1ef-b532-4826-9807-e59334e3d34b.jpg)

**Comment by Harry-Chen** [comment]
Seems duplicate with #17
