### ISSUE TITLE
Feature request : tag id as byte array

### ISSUE THREAD

**Issue by nicolasgarnet** [nfcim/flutter_nfc_kit#67]
Hi,

Would it be possible to access a tag id as a byte array ?

The string given from the library is not consistent between Android and iOS, one using little endians, the other using big endians.
It would allow reversing the byte array depending on the platform instead of handling strings.

**Comment by dangfan** [comment]
We've tested a 7-byte long ID on Android and iPhone and have not found the inconsistency you mentioned. Would you provide more information like what kind of tag you are reading? Thanks.

**Comment by Harry-Chen** [comment]
Feel free to re-open if you can find a case.
