### ISSUE TITLE
How to read card number (as printed on physical card) ?

### ISSUE THREAD

**Issue by rezarizky69** [nfcim/flutter_nfc_kit#69]
I want to read data in the form of 16 digit numbers (as printed on physical card) written on the card. Is it possible?

**Comment by kristianbinau** [comment]
Also the month, year and the digits on the back.

**Comment by Harry-Chen** [comment]
`readPPSE` in https://github.com/nfcim/nfsee/blob/master/assets/read.js#L450 might be helpful.
