### ISSUE TITLE
Flutter 3 error

### ISSUE THREAD

**Issue by Mythar** [nfcim/flutter_nfc_kit#73]
e: C:\Flutter 3\.pub-cache\hosted\pub.dartlang.org\flutter_nfc_kit-3.2.0\android\src\main\kotlin\im\nfc\flutter_nfc_kit\FlutterNfcKitPlugin.kt: (429, 13): Class 'MethodResultWrapper' is not abstract and does not implement abstract member public abstract fun error(p0: String, p1: String?, p2: Any?): Unit defined in io.flutter.plugin.common.MethodChannel.Result
e: C:\Flutter 3\.pub-cache\hosted\pub.dartlang.org\flutter_nfc_kit-3.2.0\android\src\main\kotlin\im\nfc\flutter_nfc_kit\FlutterNfcKitPlugin.kt: (449, 9): 'error' overrides nothing
e: C:\Flutter 3\.pub-cache\hosted\pub.dartlang.org\flutter_nfc_kit-3.2.0\android\src\main\kotlin\im\nfc\flutter_nfc_kit\FlutterNfcKitPlugin.kt: (452, 40): Type mismatch: inferred type is String? but String was expected

**Comment by Harry-Chen** [comment]
Duplicated with #73. Will be solved in the next release.

**Comment by samueldelamotte** [comment]
@Harry-Chen When do you think that you'll be publishing the next release?

**Comment by Harry-Chen** [comment]
See v3.3.0.
