### ISSUE TITLE
Different conflicting js versions in the plugin?

### ISSUE THREAD

**Issue by PoeMcMoe** [nfcim/flutter_nfc_kit#74]
Because flutter_nfc_kit >=3.3.0 depends on flutter_web_plugins from sdk which depends on js 0.6.3, flutter_nfc_kit >=3.3.0 requires js 0.6.3.
So, because 'project_name' depends on flutter_nfc_kit ^3.3.0 which depends on js ^0.6.4, version solving failed.

**Comment by Harry-Chen** [comment]
Version 3.3.1 solved this
