### ISSUE TITLE
Example Improvement, Include: NFCTagType.iso15693

### ISSUE THREAD

**Issue by BrayFlex** [nfcim/flutter_nfc_kit#75]
I have a NFCTagType.iso15693 and working from your example I don't see a way to decode(?) it, perhaps this would be a good addition to the example code for people who are less versed in NFC (like myself).

**Comment by BrayFlex** [comment]
https://github.com/nfcim/flutter_nfc_kit/pull/76
Merge that / Close this as you please, thanks for the library!

**Comment by dangfan** [comment]
Thank you for the PR!
