### ISSUE TITLE
Getting signature id

### ISSUE THREAD

**Issue by moein-keyvani-pur** [nfcim/flutter_nfc_kit#79]
I have a problem with getting the Signature id of an NFC card and I didn't find any solution yet, Could you please guide me to solve this problem?

_checkNFC() async {
    var availability = await FlutterNfcKit.nfcAvailability;
    if (availability == NFCAvailability.available) {
      var tag = await FlutterNfcKit.poll(timeout: const Duration(seconds: 10));
      // here i want getting card's signature 
    } else {
      await OpenSettings.openNFCSetting();
    }
  }

**Comment by dangfan** [comment]
Unfortunately, a card may follow any specification. There is no universal reading method. You have to know what kind of card you're dealing with, and the protocol to read the corresponding data.
