### ISSUE TITLE
Emulate NFC tag

### ISSUE THREAD

**Issue by ivanicsjozsef94** [nfcim/flutter_nfc_kit#80]
Hi,

I have two Android devices. On Device 1, user can build its own tag data and emulate it, so when Device 2 connects, it can receive records (for example an AAR to open a specific app) and process it.
Is there a way to emulate an NFC tag on Device?

**Comment by dangfan** [comment]
https://stackoverflow.com/questions/29122848/ndef-message-with-hce-android
