### ISSUE TITLE
How do read Mifare Classic cards for iOS

### ISSUE THREAD

**Issue by mopilo** [nfcim/flutter_nfc_kit#81]
Does the plugin provide support for reading mifare classic cards in iOS? if yes; how do I go about it?

**Comment by dangfan** [comment]
No. iOS does not support MIFARE Classic (except for NDEF).

**Comment by braysonjohn148** [comment]
> No. iOS does not support MIFARE Classic (except for NDEF).

read metadata and read & write NDEF records of tags / cards complying with:
ISO 14443 Type A & Type B (NFC-A / NFC-B / MIFARE Classic / MIFARE Plus / MIFARE Ultralight / MIFARE DESFire)
