### ISSUE TITLE
How Can I get payload text?

### ISSUE THREAD

**Issue by Huuuuuub** [nfcim/flutter_nfc_kit#83]
hello, I print the record.toString, like this:
for (var record in await FlutterNfcKit.readNDEFRecords(cached: false)) {
        debugPrint(record.toString());
     }
the result:   TextRecord: id=(empty) typeNameFormat=TypeNameFormat.nfcWellKnown type=T encoding=UTF-8 language=zh text=736B0F100048
now, I want get the "text=736B0F100048" for string type, But I do not know how to do!   please help me! thanks

**Comment by Huuuuuub** [comment]
I get it !

**Comment by Huuuuuub** [comment]
Get it.

**Comment by pantanalchain** [comment]
> 得到它。

how?

**Comment by k3v1n-uncle** [comment]
how

**Comment by k3v1n-uncle** [comment]
how

**Comment by k3v1n-uncle** [comment]
> > 得到它。
> 
> how?

do you know how to get uri?
