### ISSUE TITLE
Allow Host Card Emulation HCE on iOS

### ISSUE THREAD

**Issue by braysonjohn148** [nfcim/flutter_nfc_kit#84]
Apple has launched iOS 16.1 which allow to delete wallet meaning they allow other developers to access the API

**Comment by Harry-Chen** [comment]
As far as I know the only way to do HCE in iOS is via [PassKit](https://developer.apple.com/documentation/passkit). There's no general NFC API for HCE in iOS 16.

**Comment by braysonjohn148** [comment]
Good to hear about this workaround, sorry to ask. Can I emulate my card completely from my App, without opening the pass kit/wallet or apple pay apps?

**Comment by dangfan** [comment]
Unfortunately, no. iOS does not allow such operations.
