### ISSUE TITLE
Optional Use for supporting iPhone with no NFC Device

### ISSUE THREAD

**Issue by sadyadhan** [nfcim/flutter_nfc_kit#86]
I just use this with nfc devices and works fine.

But when i installing on device with no nfc, it automatically force close and nothing happened.

Device : Iphone 6
ios 12.4
Just have a log from iPhone 6 below :

`dyld: Library not loaded: /usr/lib/swift/libswiftCoreNFC.dylib
  Referenced from: /Users/austraramadhan/Library/Developer/CoreSimulator/Devices/C510F16D-98EE-4E48-9F7F-6FBE7B12660A/data/Containers/Bundle/Application/9D669C87-675F-4F34-8313-5DA6CAC7C1CD/Runner.app/Frameworks/flutter_nfc_kit.framework/flutter_nfc_kit
  Reason: image not found`

Hope you guys have insight or work around with this issue!
cheers!!

**Comment by Harry-Chen** [comment]
Duplicated with #8. Sorry but we won't fix this.
