### ISSUE TITLE
Change Reader Flags for Android Reader Mode

### ISSUE THREAD

**Issue by DanielPfannes** [nfcim/flutter_nfc_kit#9]
Hi,

thank you for the great NFC plugin.

I would like to turn off default android sounds while reading a NFC tag. After some research I found out that this can be done by setting the flag FLAG_READER_NO_PLATFORM_SOUNDS (see [here](https://developer.android.com/reference/android/nfc/NfcAdapter#FLAG_READER_NO_PLATFORM_SOUNDS)), which is currently not set in your plugin. Is there a way to change the Reader flags in your plugin? It would be great to be able to do this with your plugin.

**Comment by Harry-Chen** [comment]
It has been implemented now. However I will not publish it to `pub.dev` currently, you could use it directly in the form of remote git repo in your `pubspec.yaml`.

**Comment by DanielPfannes** [comment]
Thank you for the quick change! 
Unfortunately I'm getting a NullPointerException when polling for a tag with the updated version:

**Stack Trace**
![image](https://user-images.githubusercontent.com/40307553/88204932-55f63100-cc4c-11ea-9b6f-14645c9e6474.png)

**Dependency in pubspec.yaml**
![image](https://user-images.githubusercontent.com/40307553/88205047-7faf5800-cc4c-11ea-8d5c-36754dc13827.png)

**Executed Code**
`    await FlutterNfcKit.poll(
        timeout: Duration(hours: 2), 
        androidPlatformSound: false);`

**Comment by Harry-Chen** [comment]
Sorry I use the wrong parameter name on Dart side. Now it should be fixed.
