### ISSUE TITLE
Not able to build IOS app in profile or Release mode. 

### ISSUE THREAD

**Issue by JanPel** [nfcim/flutter_nfc_kit#93]
Started a flutter project with this as the only dependency. When trying to build it on the iphone, it works in Debug mode. But in release or profile mode I get the following error: 
```
    Command RuleScriptExecution failed with a nonzero exit code
    ld: framework not found Flutter
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
 ```
   The moment we remove this dependency, it works again.

**Comment by Harry-Chen** [comment]
@jiegec I believe this is not a problem from our side?
