### ISSUE TITLE
Issue facing with package flutter_nfc_kit: ^3.3.1

### ISSUE THREAD

**Issue by ShawnShaji** [nfcim/flutter_nfc_kit#98]
Greetings,
I have been facing an issue in using the library flutter_nfc_kit: ^3.3.1 for transceiving signal data on writing data in NFC tags with the package on Android devices with version 12 and above.

The stable version has not yet been released for the mentioned library until now. As a reason we are in trouble to get our project completed. The issue is attached below.

Kindly provide one solution for the same or bring a stable version for the library.
![Crash Issue](https://user-images.githubusercontent.com/112093076/221156775-8b1730d7-ae69-458b-81bd-76b1f09c440e.PNG)

**Comment by Harry-Chen** [comment]
Duplicated with #90
